### ISSUE TITLE
Raspberry Pi CV Dependencies and Libraries

### ISSUE THREAD

**Issue by awadhamza** [ucr-cs179j-team02/CS179J-Team02#20]
Unable to reference CV dependent libraries from the Pi as opposed to on a PC

**Comment by edick007** [comment]
Got this working. I had to change 3 things:
1 - the file path to the new CV model had to be configured to the Pi file system
2 - the tensorflow version needed to reference a previous version so i linked it with commands in the python script
3 - another link to the previous version was needed to the tensorflow files which will be pushed to on a new branch
