### ISSUE TITLE
Raspberry Pi power

### ISSUE THREAD

**Issue by edick007** [ucr-cs179j-team02/CS179J-Team02#21]
The Raspberry Pi is not getting enough power which is hindering the running performance. The problem is with the micro usb being used to provide power.

**Comment by edick007** [comment]
One possible solution is to use both usb power and io power - will follow up on this idea.

**Comment by awadhamza** [comment]
1. Multithreading is always an option
2. Not sure if frames are being buffered into the program, but maybe try sleeping between next loop iteration
3. Consider not scaling image upward and downward?

**Comment by awadhamza** [comment]
Planned workaround: 
1. We are going to video record a demonstration with our custom CV model running on the pi, and speed up the video to demonstrate the functionality.
2. We will be using CV on desktop for final live demonstration with the other components
