### ISSUE TITLE
CircleCI failed for my sprayer

### ISSUE THREAD

**Issue by jhur008** [ucr-cs179j-team02/CS179J-Team02#26]
My pushes on sprayer branch got a build error and failed circleci testing. Says there was no configuration. Other pushes worked so do I have to reconfigurate for sprayer?

**Comment by ghost** [comment]
I believe this is because you didn't pulled from the master branch before committing to the pr. Did you? If not, try to pull and commit again

**Comment by jhur008** [comment]
Pulled from origin/master and it worked. Was working for LED because it was a newer branch and I had already pulled when making it. Sprayer branch was older so I needed to repull. Thanks!
