### ISSUE TITLE
CV distance detection

### ISSUE THREAD

**Issue by awadhamza** [ucr-cs179j-team02/CS179J-Team02#30]
Variable scope errors when fetching and setting distance variable of classified object

**Comment by edick007** [comment]
What is the exact problem? Is the boundary where it detects distances not working properly?

**Comment by awadhamza** [comment]
I realized it became something to do with not separating out my if statements. For some reason, when I do separate them out, the logic appears to be the same, but the results are finally correct. Issue done!
